### ISSUE TITLE
Sphinx docs will break with new Doxygen due to buggy C++20 module parsing.

### ISSUE THREAD

**Issue by jevinskie** [roc-streaming/roc-toolkit#711]
Doxygen 1.9.8 and later added support for C++20 modules but the parser is buggy leading to it parsing the following section of `log.h`:

```c
typedef struct roc_log_message {
	// ...
    const char* module;
    const char* file;
	// ...
};
```

as:

```c
typedef struct roc_log_message {
	// ...
    const char*const char* file;
	// ...
};
```

I've filed PR to fix this upstream: doxygen/doxygen/pull/10777

It might work fine with a Doxygen built with clang parsing? I haven't tested.

Ugh, Flex.

**Comment by gavv** [comment]
Thanks for report! So do we need to fix anything on our side?

**Comment by jevinskie** [comment]
I think your CI pipeline is using an older doxygen that doesn’t have the original C++20 modules support so you should be safe to ignore this for now. The fix has been merged to upstream doxygen but isn’t included in a release yet. People building with a homebrew provided doxygen (most likely only Mac users, doubtful too many linuxbrew users out there) or people on rolling release Linux distros will likely see issues in the mean time though.

**Comment by gavv** [comment]
I see, thanks. Let's close it for now, at least now people can find this issue if they have problems.

PS. I've sent you a message on matrix recently (regarding FLAC), but I'm not sure it worked, I still don't quite understand how DMs are functioning there.
